version: '3.8'

services:
  ragflow:
    depends_on:
      mysql:
        condition: service_healthy
      es01:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    image: infiniflow/ragflow:v0.20.4-slim
    environment:
      - TZ=Europe/Paris
      - HF_ENDPOINT=https://hf-mirror.com
    volumes:
      - ./ragflow-logs:/ragflow/logs
      - ./service_conf.yaml.template:/ragflow/conf/service_conf.yaml.template
    networks:
      - ragflow
    restart: on-failure

  redis:
    image: redis:7.2.4-alpine3.19
    restart: on-failure
    volumes:
      - ragflow-redis:/data
    command: redis-server --appendonly yes
    networks:
      - ragflow
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  mysql:
    image: mysql:8.0.37
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: infiniflow
      MYSQL_DATABASE: rag_flow
      MYSQL_USER: ragflow
      MYSQL_PASSWORD: infiniflow
    volumes:
      - ragflow-mysql:/var/lib/mysql
    networks:
      - ragflow
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uragflow", "-pinfiniflow"]
      interval: 5s
      timeout: 2s
      retries: 10

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    restart: on-failure
    environment:
      - node.name=es01
      - cluster.name=ragflow-es
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - indices.query.bool.max_clause_count=8192
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ragflow-es:/usr/share/elasticsearch/data
    networks:
      - ragflow
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 120s

  minio:
    image: quay.io/minio/minio:RELEASE.2023-12-09T18-17-51Z
    restart: on-failure
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ragflow
      MINIO_ROOT_PASSWORD: ragflow123
    volumes:
      - ragflow-minio:/data
    networks:
      - ragflow
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ragflow-mysql:
  ragflow-es:
  ragflow-redis:
  ragflow-minio:

networks:
  ragflow:
    driver: bridge